<p class='notebook_header'><b>CS 309 - Robot Learning</b></p>
<p class='notebook_header'>Homework 1</p>
<hr class='separate' />

<p class='section_header'><b>Part 1: Linear Algebra</b></p>

Implement the following matrix/vector functions using NumPy operations.

If the function's operation isn't possible for matrix or vector inputs, return None.

In [2]:
import numpy as np

In [3]:
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return np.dot(a, b)

def divide(a, b):
    return None

def transpose(a):
    return a.T

def two_norm(a):
    return np.linalg.norm(a)

<p>Using your code from above, solve the following equations. If an operation isn't possible, put None or comment with "Not Possible".</p>

$$
u = \begin{bmatrix} 2 \\ 3 \\ 9 \end{bmatrix}, \:
v = \begin{bmatrix} -2 \\ 1 \\ 8 \end{bmatrix}
$$  


In [4]:
u = np.array([
    [2],
    [3],
    [9]
])

v = np.array([
    [-2],
    [1],
    [8]
])

$$ u + v = \begin{bmatrix} ? \end{bmatrix} $$  

$$ u - v = \begin{bmatrix} ? \end{bmatrix} $$  

$$ u * v = \begin{bmatrix} ? \end{bmatrix} $$  

$$ u \div v = \begin{bmatrix} ? \end{bmatrix} $$  


In [5]:
# YOUR CODE HERE - Completed

u_plus_v = add(u, v)
print(u_plus_v, end = '\n\n')

u_minus_v = subtract(u, v)
print(u_minus_v, end = '\n\n')

u_mult_v = multiply(u.T, v)
print(u_mult_v, end = '\n\n')

# This operation is not possible
u_div_v = None

[[ 0]
 [ 4]
 [17]]

[[4]
 [2]
 [1]]

[[71]]



$$ u^{\;T} * v = \; ? $$  

$$ u * v^{\;T} = \begin{bmatrix} ? \end{bmatrix} $$  

$$ u^{\;T} * u = \; ? $$  

$$ \left \| u \right \|_{2}^{2} = ? $$  


In [6]:
# YOUR CODE HERE - Completed

u_transpose_v = np.dot(u.T, v)
print(u_transpose_v, end = '\n\n')

u_v_transpose = np.outer(u, v.T)
print(u_v_transpose, end = '\n\n')

u_transpose_u = np.dot(u.T, u)
print(u_transpose_u, end = '\n\n')

two_norm_u = two_norm(u) # Function defined in earlier code cell
print(two_norm_u)

[[71]]

[[ -4   2  16]
 [ -6   3  24]
 [-18   9  72]]

[[94]]

9.695359714832659


<hr class='light-separate' />

$$
A = \begin{bmatrix} 1 & 6 & 5\\ 0 & -4 & -1\\ 7 & 2 & 3 \end{bmatrix}, \: 
B = \begin{bmatrix} 3 & 1 & 1\\ 4 & -1 & 7\\ 7 & 0 & 0 \end{bmatrix}
$$  


$$ A + B = \begin{bmatrix} ? \end{bmatrix} $$  

$$ A - B = \begin{bmatrix} ? \end{bmatrix} $$  

$$ A * B = \begin{bmatrix} ? \end{bmatrix} $$  

$$ A \div B = \begin{bmatrix} ? \end{bmatrix} $$  


In [6]:
# YOUR CODE HERE - Completed

A = np.array([[1, 6, 5],
              [0, -4, -1],
              [7, 2, 3]])

B = np.array([[3, 1, 1],
              [4, -1, 7],
              [7, 0, 0]])

a_plus_b = add(A, B)
print(a_plus_b, end = '\n\n')

a_minus_b = subtract(A, B)
print(a_minus_b, end = '\n\n')

a_mult_b = multiply(A, B)
print(a_mult_b)

# This operation is not possible
a_div_b = None

[[ 4  7  6]
 [ 4 -5  6]
 [14  2  3]]

[[-2  5  4]
 [-4 -3 -8]
 [ 0  2  3]]

[[ 62  -5  43]
 [-23   4 -28]
 [ 50   5  21]]


<hr class='light-separate' />

$$
C = \begin{bmatrix} 5 & 1 \\ -1 & 7 \\ 3 & 0 \end{bmatrix}
$$  


In [7]:
c = np.array([[5, 1],
              [-1, 7],
              [3, 0]])

Right Pseudo Inverse of C:
$$
\begin{bmatrix} ? \end{bmatrix}
$$  

Left Pseudo Inverse of C:
$$
\begin{bmatrix} ? \end{bmatrix}
$$  


In [8]:
# YOUR CODE HERE

right_pinv = np.linalg.pinv(c)
print(right_pinv)

left_pinv = None

[[ 0.1443299  -0.02061856  0.08591065]
 [ 0.0257732   0.13917526  0.00343643]]


<hr class='separate' />

<p class='section_header'><b>Part 2: Regression</b></p>

**Write** the equation for Ordinary Least Squares below. 

$$ y = \beta_{1} + (\beta_{2} * x) $$

**Explain** Ordinary Least Squares in terms of what it optimizes.

**Explanation:** The purpose of OLS is to draw a regression line through a collection of data that results in the smallest sum of squared residuals. This value can be found for each data point by finding the y-distance from the data point to the regression line, and squaring it. The line created that has the lowest sum, the addition of the described operation performed on each data point, is the optimal line for the data based on this regression method.

In [7]:
# Don't change this cell!
# Load in the data about the study on students
train = np.loadtxt('train.csv', delimiter=',')
x_0, x_1, x_2, y = train.T
X_train = np.array([x_0, x_1, x_2]).T
Y_train = np.expand_dims(y, 1)

test = np.loadtxt('test.csv', delimiter=',')
x_0, x_1, x_2, y = test.T
X_test = np.array([x_0, x_1, x_2]).T
Y_test = np.expand_dims(y, 1)

There was an imaginary study done on 101 students at Crest University. The study surveyed students for the amount they have spent on electronics, books, pencils, and food.

Given that the **amount students spend on electronics ($Y$)** is linearly related to the **amount they spend on books ($ X_{0} $), pencils ($ X_{1}$)**, and **food ($ X_{2}$)**, 
**implement** the Ordinary Least Squares method to model this regression problem.

The data is read in from the previous cell code. **X_train** has the input features, while **Y_train** has corresponding target outputs.

After finding a solution, try to measure the error between your predictions and the ground truth. 

In [10]:
# TODO: Create code for OLS here. DO NOT use any other libraries in your first implementation.
# TODO: Plot your regression line over the input points.

def OLS(X, y):
    theta = np.linalg.solve(np.dot(X.T, X), np.dot(X.T, y))
    return theta

# TODO: check against training data
theta_0 = OLS(X_train,Y_train)
print(theta_0, end = '\n\n')

# TODO: test your model on testing data
theta_1 = OLS(X_test, Y_test)
print(theta_1)

[[-3884.63897009]
 [-9717.11198125]
 [ 1943.82567058]]

[[-38358.89260064]
 [-95902.72468824]
 [ 19180.94784402]]


**Explain** what collinearity is.

**Explanation:** Collinearity is where two independent variables in a regression function are correlated. This means that they are closely related to one another, as through a functional relationship.

**Write** the equation for Ridge Regression below.
$$ \Theta = ((\Phi^{T} * \Phi) + (\lambda * I))^{-1} * (\Phi^{T} * y) $$

**Explain** what the purpose ridge regression and its advantages and disadvantages over OLS.

**(TODO: Write Here)**

**Implement** your regression model with ridge regression below.

In [140]:
# TODO: Create code for Ridge Regression here. DO NOT use any other libraries
# TODO: Plot your regression line over the input points.

def RR(X, y, ridge=0.001):
    pass

# TODO: check against training data
theta = RR(X_train,Y_train)


# TODO: test your model on testing data


**Explain** the differences ridge regression created for theta compared to OLS, and why these differences even existed. Also try different values for the ridge parameters and describe how they effect your results.

**(TODO: Write here)**

There are other regularizers other than ridge regression, such as LASSO. **Explain** the differences between LASSO and Ridge Regression and how it changes the solution mathematically.

**(TODO: Write here)**

In [144]:
# TODO: Create code for LASSO here
# TODO: Plot your regression line over the input points. 

def LASSO(X, y, ridge=.001):
    pass

# TODO: check against training data
theta = LASSO(X_train,Y_train)

# TODO: check against testing data

**Explain** the effect elastic nets had on your values for theta compared to OLS. Also try different values for the ridge parameters and describe how they effect your results.

**(TODO: Write here)**

**Explain** the differences between LASSO, Ridge Regression and Elastic Nets and how it changes the solution mathematically.

**(TODO: Write here)**

In [146]:
# TODO: Create code for Elastic Nets here. You can use a library such as scipy
# TODO: Plot your regression line over the input points.

def EN(X,y):
    pass

# TODO: check against training data
theta = EN(X_train,Y_train)

# TODO: check against testing data

What is the purpose of a regularizer?

**(TODO: Write here)**

Give two examples where a regularizer would give more robust models.

**(TODO: Write here)**

Explain with reference to the dataset why a regularizer achieved better performance than OLS.

**(TODO: Write here)**

<hr class='light-separate' />

Implement feature transformation to fit a line to the curve generated from the .csv file.

In [2]:
X = np.genfromtxt('feature_transform.csv', delimiter=',')
y = X[:,2].reshape(500, 1)
X = X[:,:2]

In [ ]:
# TODO: Write the lambda function phi which will transform X
# TODO: Plot the transformation and the resulting line after transforming

phi = "fill in with lambda function"
import matplotlib.pyplot as plt
plt.scatter(X[:,0],y,color=(0.0,0.5,0.0))
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

<hr class='light-separate' />

Recall what you learned about polynomial regression and explain what is happening to the model as you increase the degrees. Run the cell below and use the slider to help you.

**(TODO: Write here)**

In [ ]:
# DO NOT ALTER

import pandas as pd
import ipywidgets as widgets
from ipywidgets import interact
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

boston = datasets.load_boston()
data = pd.DataFrame(boston.data,columns=boston.feature_names)
data = pd.concat([data,pd.Series(boston.target,name='MEDV')],axis=1)

X = data[['LSTAT']].values
y = data['MEDV']

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, shuffle=True)

temp = pd.DataFrame({'x':x_train.reshape(1, 354)[0], 'y':y_train})
temp = temp.sort_values('x')
x_train = temp['x'].values.reshape(354,1)
y_train = temp['y'].values

temp = pd.DataFrame({'x':x_test.reshape(1, 152)[0], 'y':y_test})
temp = temp.sort_values('x')
x_test = temp['x'].values.reshape(152,1)
y_test = temp['y'].values

def f(degree):
    model = make_pipeline(PolynomialFeatures(degree), LinearRegression())
    model.fit(x_train,y_train)
    y_plot = model.predict(x_test)
    
    plt.scatter(x_train, y_train, s=10, color='red', alpha=.3)
    plt.scatter(x_test, y_test, s=10)

    test_sr = (y_test - y_plot)**2
    test_ssr = test_sr.sum()
    test_asr = test_ssr/len(test_sr)
    
    y_plot_train = model.predict(x_train)
    train_sr = (y_train - y_plot_train)**2
    train_ssr = train_sr.sum()
    train_asr = train_ssr/len(train_sr)
    
    plt.plot(x_test, y_plot, label="degree %d" % degree + '; Test Error: %.2f' % test_asr + '; Train Error: %.2f' % train_asr, color='green')
    plt.legend(loc='upper right')
    plt.show()
    
interact(f, degree = widgets.IntSlider(min=1, max=20, step=1, value=1))